Feature set max steps in constructor
wit-ai/node-wit pull request #107
Opened 2016-11-17 22:24 UTC by num8er

There was an issue about setting `maxSteps` globally.

The most popular solution was to modify package files, and set it inside lib/config.js.

But what if user will update packages, or what if it will be used in container or many other reasons that says that to change lib/config.js is not good idea.

Yes, I know that we can set it every time when we call `runActions` method, but why?

After [this](http://stackoverflow.com/questions/40622631/changing-wit-ai-default-max-steps) talk  in StackOverflow - I came to idea to check if there is a feature to set it in constructor.

Seems like was not.

2016-11-20 23:30 UTC, stopachka requested changes

2016-11-20 23:30 UTC, stopachka commented on lib/wit.js
> +  if(!opts.maxSteps || !Number.isInteger(opts.maxSteps)) {
this is not necessary, as the maxSteps in this.config is already enforced into being a number here -> 

https://github.com/num8er/node-wit/blob/363a23dccc5f04eb6068ce98e171c1db256989ca/lib/wit.js#L213

2016-11-20 23:30 UTC, stopachka commented on lib/wit.js
> +    const steps = maxSteps || this.config.maxSteps;
nit: would change this to -> 

```
const steps = Number.isInteger(maxSteps) ? maxSteps : this.config.maxSteps
```

2016-11-24 17:03 UTC, num8er commented
@stopachka please review

2018-05-29 20:54 UTC, l5t commented
Closing since we deprecated Stories https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5

2018-05-29 20:54 UTC, closed without merging